version: '3.9'

services:
  postgres:
    image: postgis/postgis:${POSTGRES_VERSION}
    container_name: vallengeo_db
    restart: "on-failure"
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_MULTIPLE_DATABASES: ${POSTGRES_MULTIPLE_DATABASES}
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_MULTIPLE_EXTENSIONS: postgis,postgis_tiger_geocoder,postgis_topology,fuzzystrmatch
      PGDATA: /var/lib/postgresql/data
    volumes:
    - vallengeo_db_data:/var/lib/postgresql/data
    - ./create_db.sql:/var/lib/postgresql/create-db.sql
    - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    networks:
    - vallenge
    ports:
    - ${POSTGRES_DB_DOCKER_PORT}:${POSTGRES_DB_LOCAL_PORT}
  
  geoserver:
    image: kartoza/geoserver:${GS_VERSION}
    container_name: vallengeo_geoserver
    volumes:
    - vallengeo_geoserver_data:/opt/geoserver/data_dir
    restart: on-failure
    environment:
    - GEOSERVER_DATA_DIR=${GEOSERVER_DATA_DIR}
    - GEOWEBCACHE_CACHE_DIR=${GEOWEBCACHE_CACHE_DIR}
    - GEOSERVER_ADMIN_PASSWORD=${GEOSERVER_ADMIN_PASSWORD}
    - GEOSERVER_ADMIN_USER=${GEOSERVER_ADMIN_USER}
    - INITIAL_MEMORY=${INITIAL_MEMORY}
    - MAXIMUM_MEMORY=${MAXIMUM_MEMORY}
    - GEOSERVER_CONTEXT_ROOT=${GEOSERVER_CONTEXT_ROOT}
    depends_on:
    - postgres
    networks:
    - vallenge
    ports:
    - ${GEOSERVER_PORT}:8080
    
    #  pgadmin:
    #    image: dpage/pgadmin4
    #    container_name: vallengeo_pgadmin
    #    environment:
    #      PGADMIN_DEFAULT_EMAIL: pg@admin.com
    #      PGADMIN_DEFAULT_PASSWORD: 123456
    #    depends_on:
    #    - postgres
    #    networks:
    #    - vallenge
    #    ports:
    #    - '5000:80'
    #
#    portainer:
#      image: portainer/portainer-ce:latest
#      container_name: vallengeo_portainer
#      depends_on:
#      - postgres
#      networks:
#      - vallenge
#      ports:
#      - '9443:9443'
#      restart: "on-failure"
#      volumes:
#      - data:/data
#      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  # data:
  vallengeo_db_data:
  vallengeo_geoserver_data:

networks:
  vallenge:

