spring:
# ===============================
# = BANCO DE DADOS
# ===============================
  datasource:
    hikari:
      validation-timeout: '30000'
      connection-timeout: '600000'
      initialization-fail-timeout: '2000'
      idle-timeout: '1200000'
      maximum-pool-size: '90'
      isolate-internal-queries: 'true'
      max-lifetime: '1800000'
      connection-test-query: SELECT 1
      minimum-idle: '8'
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
        temp:
          use_jdbc_metadata_defaults: 'false'
        format_sql: 'true'
        type: trace
    hibernate:
      ddl-auto: none
    show-sql: 'false'
  
# ===============================
# = FLYWAY
# ===============================
  flyway:
    enabled: false

