spring:
  main:
    allow-bean-definition-overriding: true
    
  # ===============================
  # = BANCO DE DADOS
  # ===============================
  datasource:
    url: ${DATABASE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
        temp:
          use_jdbc_metadata_defaults: 'false'
        format_sql: 'true'
        type: trace
    hibernate:
      ddl-auto: none
    show-sql: 'false'
    open-in-view: false
  
  # ===============================
  # = FLYWAY
  # ===============================
  flyway:
    enabled: false
  
  # ===============================
  # = EMAIL
  # ===============================
  mail:
    default-encoding: UTF-8
    host: ${EMAIL_HOST}
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    port: ${EMAIL_PORT}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false
  # ===============================
  # = MENSAGENS
  # ===============================
  messages:
    basename: i18n/messages

# ===============================
# SWAGGER
# ===============================
springdoc:
  swagger-ui:
    filter: false
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    defaultModelsExpandDepth: -1
    docExpansion: "none"
    path: /docs
  show-actuator: true
  api-docs:
    path: /docs

# ===============================
# SEGURANÇA
# ===============================
api:
  security:
    token:
      algorithm: HS256
      secret: ${JWT_SECRET}
      expiration: ${JWT_EXPIRATION}
      refresh: ${JWT_REFRESH}

# ===============================
# USUARIO
# ===============================
usuario:
  codigoAcesso:
    validade:
      minutos: 10

# ===============================
# LOGBACK
# ===============================
logging:
  config: classpath:logback-spring.xml

# ===============================
# VIA CEP
# ===============================
via-cep-url: https://viacep.com.br/ws

# ===============================
# OPEN FEIGN
# ===============================
feign:
  client:
    config:
      default:
        connect-timeout: 6000
        logger-level: full
        read-timeout: 6000