# ===============================
# = PORTA
# ===============================
server:
  port: ${API_PORT}

spring:
  config:
    import: optional:file:./docker/database/dev/.env[.properties]
  
  ## ===============================
  ## = BANCO DE DADOS
  ## ===============================
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true # //TODO ajustar para trazer com o lazy
        temp:
          use_jdbc_metadata_defaults: false
        type: trace
    show-sql: true

  ## ===============================
  ## = FLYWAY
  ## ===============================
  flyway:
    enabled: true
    schemas: public
    url: ${DATABASE_URL}
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
