name: CI/CD - VallenGeo

on:
  push:
    branches:
      - homolog

jobs:
  deploy-backend:
    name: Deploy Backend
    runs-on: ubuntu-latest

    steps:
    - name: Configurar acesso SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Acessar a instância Backend
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@54.232.129.154 << 'EOF'
        cd /mnt/ebs/homolog/vallengeo
        git pull origin homolog || exit 1
        cd backend
        mvn clean package || exit 1
        sudo systemctl restart vallengeo.service
        EOF

  deploy-frontend:
    name: Deploy Frontend
    runs-on: ubuntu-latest

    steps:
    - name: Configurar acesso SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Acessar a instância Frontend
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@18.231.250.52 << 'EOF'
        cd /mnt/ebs/homolog/vallengeo
        git pull origin homolog || exit 1
        cd frontend
        npm install || exit 1
        npm run build || exit 1
        sudo systemctl restart frontend.service
        EOF
